name: Generate snake animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: pit-tech
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-git-auto-commit@v3
        with:
          commit_message: "Generate Contribution Snake"
          file_pattern: dist/github-contribution-grid-snake.svg
          repository: .

      - uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg
